name: Build zip file for downloading

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build zip
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip files
      uses: actions/easyzip

