name: Build a zip file for downloading

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build zip
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip files
      uses: montudor/action-zip@v1
      with:
        args: zip ORMAPToolsV2.0.zip README.md ORMAPToolsV2.tbx AdddDimAnno.py UpdateMapIndex.py
      
